# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
